paneles/apps/home/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import *

urlpatterns = [
    path('', InicioView.as_view(), name="inicio"),
    path('imprecion/registro/<str:ids>', RegistroImpresionHistorial, name="registroimpresion"),
    path('imprecion/solicitud/<str:ids>', ContratacionView.as_view(), name="imprimir"),
    path('estadisticas/servicios/<str:idz>', BeneficiosView.as_view(), name="beneficios"),
    path('estadisticas/servicios/imprimir/<str:idz>', ImprimirView.as_view(), name="imprimirr"),
    path('estadisticas/servicios/detalles/<str:idz>', DetallesView.as_view(), name="detalles"),
    path('editar/<str:idsolicitud>', EditView.as_view(), name="editar"),
    path('duplicidad/<str:ids>', DuplicidadView.as_view(), name="duplicidad"),
    path('familiares/<str:ids>', FamiliaresView.as_view(), name="familia"),
]

paneles/paneles/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.urls import path
from django.conf import settings
from apps.home import urls

from django.contrib.auth.decorators import login_required
from apps.home.views import InicioView 
urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include('apps.home.urls') ),
    path(r'', include('apps.usuario.urls') ),
    url(r'.*/$',InicioView.as_view() )

]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

paneles/apps/home/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User 
# Create your models here.
class Direccion(models.Model):
    nombre = models.CharField(  max_length=200, verbose_name="nombre")
    estatus = models.BooleanField(verbose_name=("Estatus"), default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)    
    class Meta:
        verbose_name = "Dirección"
        verbose_name_plural = "Dirección"

    def __str__(self):
        return self.nombre

class ServiciosSolicitud(models.Model):
    nombre = models.CharField(  max_length=200, verbose_name="nombre")
    direccion = models.ForeignKey(Direccion, on_delete=models.PROTECT)
    estatus = models.BooleanField(verbose_name=("Estatus"), default=True)
    seguimiento = models.BooleanField(verbose_name=("¿Necesita seguimiento?"), default=False)
    limite = models.BooleanField(verbose_name=("¿Tiene limite de stock para la feria?"), default=False, null=True)
    cantidad = models.CharField(  max_length=200, verbose_name="cantidad de stock para la feria", default='0', null=True )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)    
    class Meta:
        verbose_name = "Servicio"
        verbose_name_plural = "Servicios"

    def __str__(self):
        return self.nombre

class PoblacionObjetivo(models.Model):
    nombre = models.CharField(  max_length=200, verbose_name="nombre")
    estatus = models.BooleanField(verbose_name=("Estatus"), default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)    
    class Meta:
        verbose_name = "Población Objetivo"
        verbose_name_plural = "Poblaciones objetivo"

    def __str__(self):
        return self.nombre

class Zona(models.Model):
    nombre = models.CharField(  max_length=200, verbose_name="nombre")
    estatus = models.BooleanField(verbose_name=("Estatus"), default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)    
    class Meta:
        verbose_name = "Lugar de atención"
        verbose_name_plural = "Lugares de atención"

    def __str__(self):
        return self.nombre


class Solicitud(models.Model):
    nombre = models.CharField(  max_length=100, verbose_name="nombre")
    appaterno = models.CharField(  max_length=100, verbose_name="apellido paterno")
    apmaterno = models.CharField(  max_length=100, verbose_name="apellido materno")
    curp = models.CharField(  max_length=50, verbose_name="CURP")
    estcivil = models.CharField(  max_length=50, verbose_name="estcivil")
    discapacidad = models.CharField(  max_length=50, verbose_name="discapacidad")
    domicilio = models.CharField(  max_length=100, verbose_name="domicilio")
    calle = models.CharField(  max_length=50, verbose_name="calle", null=True, blank=True)
    exterior = models.CharField(  max_length=50, verbose_name="exterior", null=True, blank=True)
    codigo = models.CharField(  max_length=50, verbose_name="código postal", null=True, blank=True)
    correo = models.CharField(  max_length=200, verbose_name="correo", blank=True)
    telefono = models.CharField(  max_length=200, verbose_name="teléfono", blank=True)
    sexo = models.CharField(  max_length=50, verbose_name="sexo", null=True)
    servicios = models.ManyToManyField(ServiciosSolicitud, blank=True)
    poblacion = models.ForeignKey(PoblacionObjetivo, on_delete=models.PROTECT, null=True)
    zona = models.ForeignKey(Zona, on_delete=models.PROTECT, null=True)
    detalles = models.TextField(verbose_name="Detalles", null=True,  blank=True)
    estatus = models.BooleanField(verbose_name=("Estatus"), default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)    
    class Meta:
        verbose_name = "Solicitud"
        verbose_name_plural = "Solicitud"

    def __str__(self):
        return self.nombre

class Configuracion(models.Model):
    carga = models.BooleanField(verbose_name=("Carga de solicitudes"), default=True)
    zona = models.ForeignKey(Zona, on_delete=models.PROTECT, null=True, blank=True)
    fecha = models.DateField(verbose_name="Fecha proxima atención", null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)    
    class Meta:
        verbose_name = "Configuración"
        verbose_name_plural = "Configuraciones"

    def __str__(self):
        return str(self.id)

class RegistroImpresion(models.Model):
    solcitud = models.ForeignKey(Solicitud, on_delete=models.PROTECT, null=True, blank=True)
    usuario = models.ForeignKey(User, on_delete= models.PROTECT)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)    
    class Meta:
        verbose_name = "Registro de impresiones"
        verbose_name_plural = "Registro de impresiones"

    def __str__(self):
        return str(self.id)

paneles/apps/home/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect
import json
from django.views.generic import  View
import datetime
from datetime import date
from django.urls import reverse
#from rest_framework import permissions
from .models import *
from django.db.models import Q
#from apps.utils.result_querys import filterSolicitudes

#import Email
from django.core.mail import send_mail 
from django.conf import settings
# Rest Framework
#from rest_framework.decorators import api_view
#from rest_framework.permissions import IsAuthenticated
#from rest_framework.response import Response
#from rest_framework import viewsets, status
#Serializers
#from .serializers import ServicioSerializers, SolicitantesSerializers
def email(request):

    subject = 'Bienvenido a la Junta de Reclutamiento'
    message = 'su cita ha sido registrada en nuestro citio presentarse mañana porfis'
    email_from = settings.EMAIL_HOST_USER
    recipient_list = ['rrembao00@gmail.com',]
    send_mail( subject, message, email_from, recipient_list )
    return True

def RegistroImpresionHistorial(request, ids):
    print(ids)
    solicitud = Solicitud.objects.filter(pk=ids, estatus=True)
    registro = RegistroImpresion()
    print("yeah")
    if len(solicitud)>0:
        solicitud = solicitud[0]
        registro.solcitud = solicitud
        registro.usuario = request.user
        registro.save()
        url = reverse('imprimir',  kwargs={'ids':solicitud.pk})
        return redirect(url)   
    else: 
        url = reverse('imprimir',  kwargs={'ids':'0'})
        return redirect(url)

#api prueba de rest framework
#@api_view(['GET'])
#def getFilterSolicitud(request, ec="",dis="",sexo="",pob="",zona="" ):
#    data= []
#    solicitudes = filterSolicitudes(ec,dis,sexo.upper(),pob,zona)
#    for solicitud in solicitudes:
#        servicios = solicitud.servicios.all()
#    
#        servicioserializers = []
#        serializer = SolicitantesSerializers(solicitud)
#        for servicio in servicios:
#            s_serializers = ServicioSerializers(servicio)
#            servicioserializers.append(s_serializers.data)
#        data.append({
 #           'solicitud':serializer.data,
 #           'servicios': servicioserializers
 #       })
        
  #  return Response(data)

#'''@api_view(['POST'])
#def createSolicitud(request):
#'''

class InicioView(View):
    
    def curps(self):
        array=[]
        solicitudes = Solicitud.objects.filter(estatus=True)
        for solicitud in solicitudes:
            array.append([solicitud.curp])
        return array

    def descontar(self, servicio):
        configuracion =Configuracion.objects.get(pk=1)
        if servicio.limite:
            if int(servicio.cantidad) > 0:
                solicitudes = Solicitud.objects.filter(zona=configuracion.zona, servicios__in=[servicio])
                total = len(solicitudes) +1
                if int(servicio.cantidad) <= total:
                    servicio.cantidad = 0
                    servicio.save()
            else:
                return False
        return True
    
    def get(self,request):
        configuracion = Configuracion.objects.get(pk=1)
        if configuracion.carga == True:
            if request.user.is_authenticated:
                zonas = Zona.objects.filter(estatus=True)
                servicios = ServiciosSolicitud.objects.filter(estatus=True)
                solicitudes = self.curps()
                solicitudes = json.dumps(solicitudes)
                direcciones = Direccion.objects.all()
                poblaciones = PoblacionObjetivo.objects.all()
                return  render(request,  "home/inicio.html",{'servicios':servicios,
                'direcciones':direcciones, 'poblaciones': poblaciones, 'solicitudes':solicitudes,'zonas': zonas} )
            else:
                url = reverse('login')
                return redirect(url)
        else:
            return  render(request,  "home/inicio.html" )

    def post(self,request):
        if request.user.is_authenticated:
            verificacion = Solicitud.objects.filter(curp =request.POST.get('curp'), estatus=True) 
            configuracion = Configuracion.objects.get(pk=1)
            if len(verificacion) == 0:
                solicitud = Solicitud()
                solicitud.nombre = request.POST.get('nombre')
                solicitud.appaterno = request.POST.get('paterno')
                solicitud.apmaterno = request.POST.get('materno')
                solicitud.curp = request.POST.get('curp')
                solicitud.sexo = request.POST.get('curp')[10:11]
                solicitud.estcivil = request.POST.get('estcivil')
                solicitud.discapacidad = request.POST.get('discapacidad')
                solicitud.domicilio = request.POST.get('domicilio')
                solicitud.calle = request.POST.get('calle')
                solicitud.exterior = request.POST.get('exterior')
                solicitud.codigo = request.POST.get('cp')
                solicitud.correo = request.POST.get('email')
                solicitud.telefono = request.POST.get('telefono')
                solicitud.detalles = request.POST.get('observacion')
                zona = Zona.objects.get(pk= request.POST.get('zona'))
                solicitud.zona = zona
                if request.POST.get('poblacion') != 0:
                    poblacionO = PoblacionObjetivo.objects.get(pk=request.POST.get('poblacion'))
                    solicitud.poblacion = poblacionO
                solicitud.save()
                #Servicios
                
                if request.POST.get('servicio') != "x":
                    servicio1 = ServiciosSolicitud.objects.get(pk=request.POST.get('servicio'))
                    self.descontar(servicio=servicio1)
                    solicitud.servicios.add(servicio1)  
                if request.POST.get('servicio2') != "x":
                    servicio2= ServiciosSolicitud.objects.get(pk=request.POST.get('servicio2'))
                    self.descontar(servicio=servicio2)
                    solicitud.servicios.add(servicio2)
                if request.POST.get('servicio3') != "x":
                    servicio3= ServiciosSolicitud.objects.get(pk=request.POST.get('servicio3'))
                    self.descontar(servicio=servicio3)
                    solicitud.servicios.add(servicio3)
                '''
                familiar = FamiliaresView.ValidarFamiliar(paterno=request.POST.get('paterno'),sexo=request.POST.get('curp')[10:11],materno=request.POST.get('materno'),calle=request.POST.get('calle'),codigo=request.POST.get('cp'),exterior=request.POST.get('externo') )
                print("familiar", len(familiar))
                if len(familiar) > 0:
                    url = reverse('familia', kwargs={'ids':solicitud.pk})
                    print(url)
                    return redirect(url)
                else:'''
                url = reverse('imprimir', kwargs={'ids':solicitud.pk})
                print(url)
                return redirect(url)
            else:
                idVerificacion = verificacion[0]
                url = reverse('duplicidad', kwargs={'ids':idVerificacion.pk})
                print(url)
                return redirect(url)
        else:
            url = reverse('login')
            return redirect(url)

#Reimpreción de solicitudes 
class ContratacionView(View):
    def get(self,request, ids=""):
        if ids != "0":
            solicitud = Solicitud.objects.get(pk=ids)
            servicios = solicitud.servicios.all()
            folio = str(solicitud.pk).zfill(4)
            fecha = solicitud.created.date()
            return  render(request,  "home/proceso.html",{'solicitud':solicitud,'servicios': servicios, 'id': ids, 'folio': folio, 'fecha': fecha, 'carga': False})
        else: 
           return  render(request,  "home/proceso.html",{'id':ids})
    def post(self,request, ids=""):
        curp = request.POST.get('curp')
        solicitud = Solicitud.objects.filter(curp=curp, estatus=True)
        print(solicitud)
        if len(solicitud)>0:
            solicitud = solicitud[0]
            servicios = solicitud.servicios.all()
            folio = "FB-"+str(solicitud.pk).zfill(6)
            fecha = solicitud.created.date()
            return  render(request,  "home/proceso.html",{'solicitud':solicitud,'servicios': servicios, 'id': solicitud.pk, 'folio': folio, 'fecha': fecha, 'carga': False})   
        else: 
           mensaje = True 
           return  render(request,  "home/proceso.html",{'id':"0", 'mns':mensaje})

#Apartedo de estadistica
class BeneficiosView(View):
    def ObtenerEstadisticaPoblacion(self, idz):
        poblacion = []
        poblacionObjetivo = PoblacionObjetivo.objects.all()
        if idz == "0":
            zona = Configuracion.objects.get(pk=1)
            zona = zona.zona
        else:
            zona = Zona.objects.get(pk=idz)
        for pob in poblacionObjetivo:
            if idz == "0":
                cantidad = Solicitud.objects.filter(poblacion=pob, estatus=True)
            else:
                cantidad = Solicitud.objects.filter(poblacion=pob, estatus=True, zona=zona)
            poblacion.append({
               'poblacion': pob,
               'cantidad': len(cantidad) 
            })
        return poblacion

    def get(self,request,idz="0"):
        direcciones =Direccion.objects.all()
        poblacionObjetivo = self.ObtenerEstadisticaPoblacion(idz=idz)
        if idz == "0":
            zona = Configuracion.objects.get(pk=1)
            zona = zona.zona
        else:
            zona = Zona.objects.get(pk=idz)

        print(zona)
        
        total =0
        arraytotal = []
        mujeres = 0
        hombres = 0
    
        zonas = Zona.objects.all()
        for direccion in direcciones:
            servicios = ServiciosSolicitud.objects.filter(direccion= direccion)
            array = []
            total =0
            

paneles/templates/home/beneficios.html
{% extends "base/base.html" %}
{% load staticfiles %}

{% block extracss %}
<style>
  * {
    font-family: sans-serif;
    font-weight: 100;
    font-size: 20px;
  }

  a{
    text-decoration: none !important;
  }

  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
    .cont_rowmin{
      padding-top: 3%;
      margin-bottom: 6%;
    }
    .cont_row{
      
      margin-bottom: 2%;
    }
  }

  @media (max-width: 768px) {
    #id_tabla {
      width: 100% !important;
    }

    .rowmin{
      width: 100% !important;
     
    }
    .tex-p{
      font-size: 17px !important;
    }
    .cont_rowmin{
      width: 100%;
      margin-left: 5% !important;
      margin-bottom: 6%;
      
    }
    .cont_row{
      width: 100%;
      margin-left: 5% !important;
      margin-bottom: 6%;
    }
  }
  .img_content {
    margin: 10px;
    
    line-height: 115px;
    text-align: center;
    
    background-repeat: no-repeat;
    background-position: center;
    background-size: contain;

}

li:hover{
  border-bottom: 3px solid #691C32;
  transition: border-color 1s ease;
  
}
.color-boton{
  background-color: #9A0E44 !important;
  color: white;
}

.color-boton:hover{
  background: #c0527c !important;
  color: white;
}
</style>
{% endblock extracss %}

{% block content%}</h1>
<div class="position-relative overflow-hidden mt-5 p-3 p-md-5 m-md-3 bg-light" >
  {% if configuracion.carga %}
    {% if request.user.is_authenticated %}
      <div class="container mt-5" align="right"><a class="btn  color-boton" href="{%url 'imprimirr' idz=idz%}">Descargar Estadisticas <i class="fas fa-file-download"></i> </a></div>
    {% else %}
      <div class="container mt-5" align="right"></div>
    {% endif %}
  {% else %}
    <div class="container mt-5" align="right"></div>
  {% endif %}
  <div class="mt-5" style="background-color: #ebecec; padding:30px; border-radius:18px;">
   <b> <h2 class="text-center"  style="font-weight: bold;">Estadística de Solicitudes</h2></b>
   <br>
    
   <div class="container-fluid justify-content-center cont_row" style="align-items: center; margin-left:28%;">
    <div class="row rowmin justify-content-center" style="width: 45%; border-bottom: 1px solid #691C32" >
   Cambiar de Localidad <samp style="color:#9A0E44"></samp> <br>
   <select name="localidad" class="select form-control mb-3" required="" id="id_zona"> 
     <option value="0" selected="" disabled>Seleccione una Localidad</option> 
     <option value="0" >TODAS</option> 
     {% for zona in zonas %}
       <option value="{{zona.pk}}" >{{zona.nombre}}</option>
     {% endfor %}
   </select> 
    </div>
    
   </div>
  
   <h5 class="text-center"  style="font-weight: bold;">{{localidad}}</h5>
  <!--Estadistica general de hombres mujeres y discapacitados-->
  <div class="container-fluid justify-content-center cont_rowmin" style="align-items: center; margin-left:28%;">
   <div class="row rowmin justify-content-center" style="width: 45%; border-bottom: 1px solid #691C32" >
    <div class="col-sm-10 col-10 ">
      <i class="far fa-file-alt " style="align-items: center; "></i>&nbsp; Total de Solicitudes
    </div>
    <div class="col-2 col-sm-2 text-center">
      <b style="color: #691C32; font-size:30px; font-weight: bold; ">{{total_solicitudes}}</b>
    </div>
  </div>

   <div class="row rowmin justify-content-between" style="width: 45%; border-bottom: 1px solid #691C32" >
    <div class="col-sm-10 col-10">
      <i class="fas fa-male"></i>&nbsp; Total de Hombres
    </div>
    <div class="col-2 col-sm-2 text-center">
      <b style="color: #691C32; font-size:30px; font-weight: bold;">{{hombres}}</b>
    </div>
  </div>
    <div class="row rowmin justify-content-between" style="width: 45%; border-bottom: 1px solid #691C32 " >
      <div class="col-sm-10 col-10">
        <i class="fas fa-female"></i>&nbsp; Total de Mujeres
      </div>
      <div class="col-2 col-sm-2 text-center">
        <b style="color: #691C32; font-size:30px; font-weight: bold;">{{mujeres}}</b>
      </div>
    </div>
    <div class="row rowmin justify-content-between" style="width: 45%; border-bottom: 1px solid #691C32" >
      <div class="col-sm-10 col-10">
        <i class="fas fa-wheelchair" style="align-items: center;"></i></i>&nbsp; Total de personas con discapacidad
      </div>
      <div class="col-2 col-sm-2 text-center">
        <b style="color: #691C32; font-size:30px; font-weight: bold; ">{{discapacidades}}</b>
      </div>
    </div>
  </div>

  <div class=" container-fluid mt-5" >
    <h3 class="text-center" style="font-weight: bold; margin-bottom:2%">Población Objetivo</h3>
    <div class="row">     
    {% for pob in poblacion %}
    <div class="col-md-4 mb-1" style="font-weight: bold; border: solid 1px; border-bottom:solid 4px #691C32">
      <div class="row rowmin justify-content-between"  >
        <div class="col-sm-8 col-8">
          {{pob.poblacion}}
        </div>
        <div class="col-4 col-sm-4 text-center">
          <b style="color: #691C32; font-size:30px; font-weight: bold; ">{{pob.cantidad}}</b>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  </div>
</div>
  <div class="container-fluid text-center" style="margin-top: 10%;">

  {% for estadistica in estadisticas %}
      <h3 class="mt-3" style="font-weight: bold;">{{estadistica.direccion}}</h3>
      
      <div  align="right">
        <div class="row rowmin justify-content-between"  style="width: 30%;">
          <div class="col-sm-10 col-10" style="font-weight: bold;">
            Total de servicios
          </div>
          <div class="col-2 col-sm-2 text-center">
            <b style="color: #691C32; font-weight: bold; "> {{estadistica.total}}</b>
          </div>
        </div>
      </div>
      
       
        <div class="table-responsive" style=" margin-bottom:6%">
            <table id="id_tabla_actividades" style="border: solid 1px #691C32;" class="table">
                <thead class="color-boton" style="background-color: #691C32; color:white; font-weight:bold">
                    <tr>
                        <th>Servicio</th>
                        <th>Cantidad</th>
                    </tr>
                </thead>
                <tbody class="bg-transparent">
                    {% for servicio in estadistica.servicios %}
                        <tr>
                            <td scope="row" style="font-weight:bold"> {{servicio.servicio}}</td>
                            <td style="width: 20%; font-weight:bold; color:#691C32">{{servicio.cantidad}}</td>
                            
                        </tr>
                        {% endfor %}
                </tbody>
            </table>
        </div>
  {% endfor %}
</div>
</div>

{% endblock content %}
{% block extrascripts %}

    <script>
      
      $(document).ready(function () {
        $( "#id_zona" ).change(function() {
          var url = window.location.toString()
          var urlsplit= url.split("/");
          var localidad = document.getElementById("id_zona").value;
      
          var URLactual = "/estadisticas/servicios/"+localidad;
          window.location.href = URLactual;   
      }); 


        tel_mostrar = true
        email_mostrar = true

        $(".telefonos").hide()
        $(".correos").hide()

        $(".whatsapp").click(function() {
          if (tel_mostrar==true){
            $(".telefonos").show()
            tel_mostrar=false
          }else{
            $(".telefonos").hide()
            tel_mostrar=true
          }
          });

       
       
        $(".email").click(function() {
          if (email_mostrar==true){
            $(".correos").show()
            email_mostrar=false
          }else{
            $(".correos").hide()
            email_mostrar=true
          }
          });
        })
      

        
    </script>
{% endblock %}

paneles/templates/home/contactos.html
{% extends "base/base.html" %}
{% load staticfiles %}

{% block extracss %}
<style>
  * {
    font-family: sans-serif;
    font-weight: 100;
    font-size: 20px;
  }

  a{
    text-decoration: none !important;
  }

  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
  }
  .img_content {
    margin: 10px;
    
    line-height: 115px;
    text-align: center;
    
    background-repeat: no-repeat;
    background-position: center;
    background-size: contain;

}

li:hover{
  border-bottom: 3px #691C32;
  transition: border-color 1s ease;
  
}

</style>
{% endblock extracss %}

{% block content%}



<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
  <div class="col-md-5 p-lg-5 mx-auto my-5">
    <h1 class="display-4 font-weight-normal">Bienvenido</h1>
    <p class="lead font-weight-normal">un lema</p>
    <a class="btn btn-outline-secondary" href="#">Conocenos</a>
  </div>

</div>
<!-- indicar que el contenido de el texto es seguro {{servicio.descripcion| safe}}-->

<div class="d-md-flex flex-md-equal w-100 my-md-3 pl-md-3">
  {% for item in servicios %}
  <div class="div-gasadi mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
    <div class="my-3 py-3">
      <h2 class="display-5">{{item.titulo}}</h2>
      <p class="lead">{{item.subtitulo}}</p>
    </div>
    <div class="bg-light shadow-sm mx-auto img_content" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0; background-image: url({{item.imagen.url}}); ">

    </div>
  </div>
  {% endfor %}
  <!--
  <div class="bg-light mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
    <div class="my-3 p-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-dark shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
  -->
</div>

<div class="d-md-flex flex-md-equal w-100 my-md-3 pl-md-3">
  <div class="bg-light mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
    <div class="my-3 p-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-white shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
  <div class="bg-light mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
    <div class="my-3 py-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-white shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>

  
</div>


{% endblock content %}
{% block extrascripts %}

    <script>
      
      $(document).ready(function () {
        tel_mostrar = true
        email_mostrar = true

        $(".telefonos").hide()
        $(".correos").hide()

        $(".whatsapp").click(function() {
          if (tel_mostrar==true){
            $(".telefonos").show()
            tel_mostrar=false
          }else{
            $(".telefonos").hide()
            tel_mostrar=true
          }
          });

       
       
        $(".email").click(function() {
          if (email_mostrar==true){
            $(".correos").show()
            email_mostrar=false
          }else{
            $(".correos").hide()
            email_mostrar=true
          }
          });
        })
      

        
    </script>
{% endblock %}